"use client"

import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { FileText, CheckCircle, Clock } from "lucide-react"

// HARDCODED SUPABASE CREDENTIALS
const SUPABASE_URL = "https://leolsqraajajphguipzx.supabase.co"
const SUPABASE_ANON_KEY = "sb_publishable_DN_9JJ38bQZxkrfrTKqNcQ_rEEPjE4J"

export function ApprovalsPanel() {
  const [applications, setApplications] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function fetchApplications() {
      try {
        const response = await fetch(`${SUPABASE_URL}/rest/v1/application?select=*`, {
          headers: {
            apikey: SUPABASE_ANON_KEY,
            Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
          },
        })
        if (response.ok) {
          const data = await response.json()
          // Reverse the array so the newest submissions show up at the top
          setApplications(data.reverse())
        }
      } catch (error) {
        console.error("Failed to fetch:", error)
      } finally {
        setLoading(false)
      }
    }
    fetchApplications()
  }, [])

  // STEP 4: THE FAKE AI REGULATORY ENGINE
  const getRequirements = (industry: string) => {
    const normalizedIndustry = industry?.toLowerCase() || ""
    
    if (normalizedIndustry.includes("manufacturing")) {
      return ["Fire NOC", "Pollution Board Approval"]
    }
    if (normalizedIndustry.includes("technology") || normalizedIndustry.includes("it")) {
      return ["Local Authority Permission", "Data Privacy Audit"]
    }
    if (normalizedIndustry.includes("energy")) {
      return ["Environmental Clearance", "Grid Connection Approval"]
    }
    return ["Standard Business License", "Tax Registration"]
  }

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-6 p-6">
      <div className="flex flex-col gap-1.5">
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">
          Review Status & Approvals
        </h1>
        <p className="text-sm text-muted-foreground">
          Track your submitted applications and view regulatory requirements generated by the compliance engine.
        </p>
      </div>

      {loading ? (
        <div className="space-y-4">
          {/* Replaced the missing Skeleton component with native Tailwind CSS */}
          <div className="h-32 w-full animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800" />
          <div className="h-32 w-full animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800" />
        </div>
      ) : applications.length === 0 ? (
        <Card>
          <CardContent className="p-12 text-center text-muted-foreground">
            No applications found. Submit a new application to see it here.
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4">
          {applications.map((app, index) => {
            const requirements = getRequirements(app.industry_type)
            
            return (
              <Card key={index}>
                <CardHeader className="pb-3">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-xl">{app.company_name}</CardTitle>
                    <Badge variant="secondary" className="flex items-center gap-1.5 bg-yellow-100 text-yellow-800 hover:bg-yellow-100">
                      <Clock className="size-3.5" /> Pending Review
                    </Badge>
                  </div>
                  <CardDescription>
                    Industry: <span className="font-medium capitalize">{app.industry_type}</span> | Investment: {app.investment_size}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="rounded-md border bg-slate-50 p-4">
                    <h4 className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-900">
                      <FileText className="size-4 text-blue-600" />
                      AI Engine: Required Documentation
                    </h4>
                    <ul className="flex flex-col gap-2 text-sm text-slate-700">
                      {requirements.map((req, i) => (
                        <li key={i} className="flex items-center gap-2">
                          <CheckCircle className="size-4 text-green-600" />
                          {req}
                        </li>
                      ))}
                    </ul>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )
    }
    </div>
  )
}
